####
# ATENTION:
# Replace all occurences of sandbox with your project's name
####

# v2 syntax
version: '2'

# Named volumes
volumes:
  # Postgres Data
  simple-tw-postgres-data:
    driver: local


services:
  # Postgres (9.6)
  postgres:
    image: ambientum/postgres:9.6
    container_name: simple-tw-postgres
    volumes:
      - simple-tw-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=simple-tw
      - POSTGRES_USER=simple-tw
  # PHP (with Caddy)
  app:
    image: ambientum/php:7.1-caddy
    container_name: simple-tw-app
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
    links:
      - postgres        

