####
# ATENTION:
# Replace all occurences of sandbox with your project's name
####

# v2 syntax
version: '2'

# Named volumes
volumes:
  # Postgres Data
  simple-tw-postgres-data:
    driver: local


services:
  # Postgres (9.6)
  postgres:
    image: ambientum/postgres:9.6
    container_name: simple-tw-postgres
    volumes:
      - simple-tw-postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=yanc0302
      - POSTGRES_DB=homestead
      - POSTGRES_USER=postgres
  # PHP (with Caddy)
  app:
    image: ambientum/php:7.2
    container_name: simple-tw-app
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
    links:
      - postgres

  # Laravel Queues
  queue:
    image: ambientum/php:7.0
    container_name: sandbox-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - postgres
